const exitCodes = {
    OK: 0,
    UNHANDLED_EXCEPTION: 1,
    CONFIG_PARSE_ERROR: 2,
    CONFIG_NOT_FOUND: 3,
    CONFIG_NOT_VALID: 4,
    INSUFFICIENT_PERMISSIONS: 5,
    NO_REPOSITORIES_UPSERTED: 6,
    SOME_REPOSITORIES_COULD_NOT_BE_UPSERTED: 7
};

module.exports = exitCodes;